version: 2.1


parameters:
  full_plan_apply: 
    type: string
    default: ""

orbs:
  aws-cli: circleci/aws-cli@3.1.4
jobs:
  aws-cli-cred-setup: 
    executor: aws-cli/default
    steps: 
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
  init-and-plan:
    docker: 
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps: 
      - checkout
      - run: 
          name: terraform init and plan
          command: | 
            cd infrastructure
            terraform init -input=false
            terraform plan
  full-apply:
    docker: 
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps: 
      - checkout
      - run: 
          name: terraform manually do full apply
          command: | 
            cd infrastructure
            terraform init -input=false
            terraform apply -input=false -auto-approve 
workflows: 
  on-merge:
    jobs: 
      - aws-cli-cred-setup:
          filters: 
            branches: 
              only: main
      - init-and-plan:
          requires:
            - aws-cli-cred-setup
          filters: 
            branches: 
              only: main
  manual-full-apply:
    when: << pipeline.parameters.full_plan_apply >>
    jobs:
      - full-apply 